#!/usr/bin/env bash
# knowledge/scripts/scan-projects.sh
# Usage: bash knowledge/scripts/scan-projects.sh
# Run from anywhere — resolves root automatically.
# Compatible with bash 3.2+ (macOS default)

ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
OUTPUT="$ROOT_DIR/knowledge/PROJECTS.md"

echo "Scanning projects in: $ROOT_DIR"
echo "Output: $OUTPUT"

# Return cluster name for a given project name prefix
get_cluster() {
  local name="$1"
  case "$name" in
    oms-*)             echo "OMS" ;;
    omnia-* | Omnia-*) echo "Omnia" ;;
    pmp-*)             echo "PMP" ;;
    daas-*)            echo "DAaS" ;;
    poc-*)             echo "POC" ;;
    adapter-*)         echo "Adapter" ;;
    e-ordering)        echo "E-Ordering" ;;
    *)                 echo "Other" ;;
  esac
}

# Extract stack hint from a project's CLAUDE.md
get_stack() {
  local project_dir="$1"
  local claude_file="$project_dir/CLAUDE.md"
  if [[ -f "$claude_file" ]]; then
    local stack
    stack=$(grep -i "framework\|stack\|NestJS\|Next\.js\|React\|Angular\|Vue\|Python\|Go\|Ruby" \
      "$claude_file" 2>/dev/null | head -2 | tr '\n' ' ' | sed 's/|//g' | xargs 2>/dev/null)
    [[ -n "$stack" ]] && echo "${stack:0:60}" || echo "—"
  else
    echo "—"
  fi
}

# Collect all project names (skip non-project dirs)
collect_projects() {
  for dir in "$ROOT_DIR"/*/; do
    name=$(basename "$dir")
    [[ "$name" == .* ]]              && continue
    [[ "$name" == "node_modules"* ]] && continue
    [[ "$name" == "specs" ]]         && continue
    [[ "$name" == "knowledge" ]]     && continue
    [[ "$name" == "dist" ]]          && continue
    [[ "$name" == "logs" ]]          && continue
    [[ "$name" == "coverage" ]]      && continue
    [[ "$name" == "test" ]]          && continue
    [[ "$name" == "src" ]]           && continue
    [[ "$name" == "app" ]]           && continue
    [[ "$name" == "architecture" ]]  && continue
    [[ "$name" == "PMP" ]]           && continue
    echo "$name"
  done
}

# Print one cluster section given a cluster name and list of projects
print_cluster() {
  local cluster_name="$1"
  local projects_in_cluster=()

  # Collect all projects belonging to this cluster
  while IFS= read -r proj; do
    c=$(get_cluster "$proj")
    [[ "$c" == "$cluster_name" ]] && projects_in_cluster+=("$proj")
  done < <(collect_projects)

  [[ ${#projects_in_cluster[@]} -eq 0 ]] && return

  echo "## $cluster_name Cluster"
  echo ""
  echo "| Project | Has CLAUDE.md | Has docs/ | Stack (from CLAUDE.md) |"
  echo "|---------|:---:|:---:|------------------------|"

  for proj in "${projects_in_cluster[@]}"; do
    proj_dir="$ROOT_DIR/$proj"
    has_claude="❌"
    [[ -f "$proj_dir/CLAUDE.md" ]] && has_claude="✅"
    has_docs="❌"
    [[ -d "$proj_dir/docs" ]] && has_docs="✅"
    stack=$(get_stack "$proj_dir")
    echo "| \`$proj\` | $has_claude | $has_docs | $stack |"
  done
  echo ""
}

# Build output file
{
  echo "# Project Index — git-central"
  echo ""
  echo "> Auto-generated by \`knowledge/scripts/scan-projects.sh\`"
  echo "> Last updated: $(date '+%Y-%m-%d %H:%M:%S')"
  echo "> To regenerate: \`bash knowledge/scripts/scan-projects.sh\`"
  echo ""

  for cluster in "OMS" "Omnia" "PMP" "DAaS" "E-Ordering" "Adapter" "Other" "POC"; do
    print_cluster "$cluster"
  done

} > "$OUTPUT"

project_count=$(grep -c '^\| \`' "$OUTPUT" 2>/dev/null || echo 0)
echo "Done! knowledge/PROJECTS.md updated."
echo "Projects scanned: $project_count"

# ── Update knowledge/CLAUDE.md project summaries ──────────────────────────────

KNOWLEDGE_CLAUDE="$ROOT_DIR/knowledge/CLAUDE.md"

# Extract port from a project's CLAUDE.md
get_port() {
  local claude_file="$1/CLAUDE.md"
  [[ ! -f "$claude_file" ]] && echo "" && return
  grep -iE 'Port.*[0-9]{4}|[0-9]{4}.*[Pp]ort' "$claude_file" 2>/dev/null \
    | grep -oE '[0-9]{4}' | head -1
}

# Extract one-line description from project CLAUDE.md (first non-generic, non-empty line)
get_desc() {
  local claude_file="$1/CLAUDE.md"
  [[ ! -f "$claude_file" ]] && echo "" && return
  grep -v '^#\|^$\|^>\|This file provides guidance\|claude-mem\|Recent Activity\|Auto-generated\|---|===' \
    "$claude_file" 2>/dev/null | head -3 | tr '\n' ' ' | sed 's/  */ /g' | xargs 2>/dev/null | cut -c1-100
}

# Build summaries block
build_summaries() {
  echo "| Project | Port | Stack | Docs |"
  echo "|---------|:----:|-------|:----:|"
  for cluster in "OMS" "Omnia" "PMP" "DAaS" "E-Ordering" "Adapter" "Other" "POC"; do
    while IFS= read -r proj; do
      c=$(get_cluster "$proj")
      [[ "$c" != "$cluster" ]] && continue
      proj_dir="$ROOT_DIR/$proj"
      [[ ! -f "$proj_dir/CLAUDE.md" ]] && continue
      port=$(get_port "$proj_dir")
      stack=$(get_stack "$proj_dir")
      has_docs="—"
      [[ -d "$ROOT_DIR/knowledge/${proj}-docs" ]] && has_docs="[docs](${proj}-docs/)"
      port_str="${port:+\`:$port\`}"
      echo "| \`$proj\` | ${port_str:-—} | $stack | $has_docs |"
    done < <(collect_projects)
  done
}

# Replace between markers using Python3 (handles multi-line safely on macOS)
SUMMARIES=$(build_summaries)

python3 - "$KNOWLEDGE_CLAUDE" "$SUMMARIES" << 'PYEOF'
import sys

path    = sys.argv[1]
content = sys.argv[2]

START = '<!-- AUTO-GENERATED:project-summaries:start -->'
END   = '<!-- AUTO-GENERATED:project-summaries:end -->'

with open(path, 'r') as f:
    text = f.read()

si = text.find(START)
ei = text.find(END)
if si == -1 or ei == -1:
    print('Warning: markers not found in', path)
    sys.exit(0)

new_text = text[:si + len(START)] + '\n' + content + '\n' + text[ei:]
with open(path, 'w') as f:
    f.write(new_text)

print('knowledge/CLAUDE.md updated.')
PYEOF
